language: python 
os: linux

python:
  - "3.7"

before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools

install:
  - eval "$(pyenv init --path)"
  - pip install codecov
  - pip install pytest-cov
  - pip install -e .
 
script:
  - pytest -s
  
after_success:
  - codecov
