language: python 
os: linux

python:
  - "3.7"

before_install:
  - pip install --upgrade pip

install: 
  - pip install codecov
  - pip install pytest-cov
  - pip install . -e
 
script:
  - pytest -s
  
after_success:
  - codecov
